version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=production-secret-key-change-this
      - DATABASE_URL=sqlite:///data.sqlite
      - FLASK_ENV=production
    volumes:
      - portfolio_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  portfolio_data:
