name: Portfolio CMS CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Initialize database
      run: |
        python -c "from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all()"
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short
        
    - name: Test application startup
      run: |
        python -c "from app import create_app; app = create_app(); print('✓ Application starts successfully')"
